// Generated by CoffeeScript 1.8.0
(function() {
  module.exports.encode = (function(_this) {
    return function(buffer, id) {
      var identifier;
      identifier = new Buffer(4);
      identifier.writeUInt32BE(id, 0);
      return Buffer.concat([identifier, buffer], buffer.length + 4);
    };
  })(this);

  module.exports.decode = (function(_this) {
    return function(buffer) {
      return {
        identifier: buffer.slice(0, 4).readUInt32BE(0),
        chunk: buffer.slice(4, buffer.length)
      };
    };
  })(this);

}).call(this);

//# sourceMappingURL=buffer-decoder.js.map
