// Generated by CoffeeScript 1.8.0
(function() {
  module.exports.parseAddress = function(address) {
    var host, port, _ref;
    if (typeof address === 'number') {
      port = address;
    } else {
      _ref = address.split(':'), host = _ref[0], port = _ref[1];
      if (/^\d+$/.test(host)) {
        port = host;
        host = null;
      }
      port = parseInt(port);
    }
    if (host == null) {
      host = '127.0.0.1';
    }
    return {
      host: host,
      port: port
    };
  };

}).call(this);

//# sourceMappingURL=utils.js.map
